import type { Photo } from './types';

export const photos: Photo[] = [
    { id: 1, title: 'Boiling Point', category: 'Commercial', year: '2024', image: 'https://i.ibb.co.com/bgDKXMjp/S3-N0-LOG-8.jpg', description: 'Capturing raw emotion and authentic moments.' },
    { id: 5, title: 'Ravina On Pose', category: 'Portrait', year: '2023', image: 'https://i.ibb.co.com/bj1VjhX4/S3-N0-LOG-12.jpg', description: 'High-end portrait and fashion campaign.' },
    { id: 6, title: 'Las Flores Pink Bourbon Beans Promo', category: 'Commercial', year: '2023', image: 'https://i.ibb.co.com/M53Q4YH3/S3-N0-LOG-23.jpg', description: 'Minimalist product shots with dramatic lighting.' },
    { id: 7, title: 'Brand Story', category: 'Commercial', year: '2023', image: 'https://i.ibb.co.com/93qzCY2N/snolog-5.jpg', description: 'Expansive landscape for automotive commercial.' },
    { id: 8, title: 'Studio Portrait', category: 'Commercial', year: '2024', image: 'https://i.ibb.co.com/1JfWkQYV/DSC00495.jpg', description: 'Clean studio lighting for beauty campaign.' },
    { id: 2, title: 'Urban Landscapes', category: 'Portrait', year: '2024', image: 'https://i.ibb.co.com/0R8vVq6g/S3-N0-LOG-2.jpg', description: 'Exploring natural and urban landscapes.' },
    { id: 3, title: 'Capturing Bernadya on stage.', category: 'Event', year: '2024', image: 'https://i.ibb.co.com/G48sf2NH/S3-N0-LOG-382.jpg', description: 'Documenting everyday life and candid moments.' },
    { id: 4, title: 'Wedding Moments', category: 'Portrait', year: '2024', image: 'https://i.ibb.co.com/Q3R5QZFM/S3-N0-LOG-2.jpg', description: 'Preserving precious memories of special events.' },
    { id: 71, title: '', category: 'Commercial', year: '2023', image: 'https://i.ibb.co.com/RF2ShDQ/S3-N0-LOG-62.png', description: 'Minimalist product shots with dramatic lighting.' },
    { id: 81, title: '', category: 'Portrait', year: '2024', image: 'https://i.ibb.co.com/V0RhGpnq/S3-N0-LOG-20.jpg', description: 'Minimalist product shots with dramatic lighting.' },
    { id: 9, title: '', category: 'Portrait', year: '2023', image: 'https://i.ibb.co.com/xtCBGTFD/S3-N0-LOG-26.png', description: 'Minimalist product shots with dramatic lighting.' },
    { id: 10, title: '', category: 'Portrait', year: '2023', image: 'https://i.ibb.co.com/Q7cV6RB2/S3-N0-LOG-333.png', description: 'Minimalist product shots with dramatic lighting.' },
    { id: 11, title: '', category: 'Portrait', year: '2023', image: 'https://i.ibb.co.com/9kD7Z3ww/DSC07487.jpg', description: 'Minimalist product shots with dramatic lighting.' },
    { id: 12, title: '', category: 'Portrait', year: '2023', image: 'https://i.ibb.co.com/dNTHVrc/DSC02462.jpg', description: 'Minimalist product shots with dramatic lighting.' },
    { id: 13, title: '', category: 'Commercial', year: '2023', image: 'https://i.ibb.co.com/zVDp0Vw0/S3-N0-LOG-19.jpg', description: 'Minimalist product shots with dramatic lighting.' },
    { id: 14, title: '', category: 'Potrait', year: '2023', image: 'https://i.ibb.co.com/B2x1jj5t/DSC09230.jpg', description: 'Minimalist product shots with dramatic lighting.' },
    { id: 15, title: '', category: 'Commercial', year: '2023', image: 'https://i.ibb.co.com/j9FSjz8x/S3-N0-LOG-7.jpg', description: 'Minimalist product shots with dramatic lighting.' },
    { id: 16, title: 'Latte Art', category: 'Commercial', year: '2023', image: 'https://i.ibb.co.com/9HpST4jD/LRM-20230609-143215.jpg', description: 'Minimalist product shots with dramatic lighting.' },
    { id: 17, title: '', category: 'Commercial', year: '2024', image: 'https://i.ibb.co.com/23JsYKKB/S3-N0-LOG-14-of-14.jpg', description: 'Minimalist product shots with dramatic lighting.' },
    { id: 171, title: 'Kadapi Fadli', category: 'Event', year: '2023', image: 'https://i.ibb.co.com/DDtnS1Xr/S3-N0-LOG-27.jpg', description: 'Minimalist product shots with dramatic lighting.' },
    { id: 18, title: 'Masno Milk & Coffee', category: 'Commercial', year: '2026', image: 'https://i.ibb.co.com/WWByV8dr/Artboard-3-6.png', description: '' },
    { id: 19, title: 'Las Flores Beans', category: 'Commercial', year: '2024', image: 'https://i.ibb.co.com/m5NdKsXJ/las-flores.png', description: '' },
    { id: 20, title: 'Kadapi Fadli at Cotta Haus', category: 'Event', year: '2023', image: 'https://i.ibb.co.com/rKc2SJBF/S3-N0-LOG-33.jpg', description: '' },
    { id: 21, title: 'Geisha at Cotta Haus', category: 'Event', year: '2023', image: 'https://i.ibb.co.com/ZR6fDRG0/S3-N0-LOG-69.jpg', description: 'Minimalist product shots with dramatic lighting.' },
    { id: 22, title: 'Geisha at Cotta Haus', category: 'Event', year: '2023', image: 'https://i.ibb.co.com/bRqchrDx/S3-N0-LOG-287.jpg', description: ' ' },
];